// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wowttldmxhrtjvaavfth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvd3R0bGRteGhydGp2YWF2ZnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjEyMzgsImV4cCI6MjA2MDczNzIzOH0.rtaXWG4WiS5hfflnelsrrPv43tR2GQTa1n_y4O2lBak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);